name: GitHub CI

on: [push]

jobs:
  build:

    name: Tracker Update
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        brew install curl gawk gnu-sed findutils
        which curl awk gawk sed gsed xargs gxargs
