name: GitHub CI

on:
  schedule:
    - cron:  '00 */6 * * *'

jobs:
  build:

    name: Tracker Update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          curl -fs -C - \
            https://raw.githubusercontent.com/ngosang/trackerslist/master/{trackers_all,trackers_all_ws,trackers_all_ip}.txt \
            https://newtrackon.com/api/stable?include_ipv6_only_trackers=0 \
            | awk NF \
            | sed ':a;N;s/\n/,/g;ta' \
            | xargs -r -n 1 -I '{}' \
            sed -i '/^bt-tracker\=/{h;s#\(^bt-tracker\=\).*$#\1{}#};${x;/^$/{s##bt-tracker\={}#;H};x}' \
            .config/aria2/aria2.conf .config/aria2/aria2_rpc.conf

      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Apply automatic changes
