name: GitHub CI

on:
  schedule:
    - cron:  '0/1 * * * *'

jobs:
  build:

    name: Tracker Update
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          brew update
          brew install curl gawk gnu-sed findutils
          curl -fs -C - \
            https://raw.githubusercontent.com/ngosang/trackerslist/master/{trackers_all,trackers_all_ws,trackers_all_ip}.txt \
            https://newtrackon.com/api/stable?include_ipv6_only_trackers=0 \
            | gawk NF \
            | gsed ':a;N;s/\n/,/g;ta' \
            | gxargs -r -n 1 -I '{}' \
            gsed -i '/^bt-tracker\=/{h;s#\(^bt-tracker\=\).*$#\1{}#};${x;/^$/{s##bt-tracker\={}#;H};x}' \
            aria2.conf
            grep -E '^bt-tracker\=' aria2.conf

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
